### ISSUE TITLE
Новый список для изучения слепой печати

### ISSUE THREAD

**Issue by fey** [Hexlet/interactive-courses#47]
Добавить ссылки на сервисы для изучения, прокачки и тренировки слепой печати. Только бесплатные сервисы.

Пример 
https://www.ratatype.ru/
https://monkeytype.com/
https://www.keybr.com/ru/index
https://typerun.top/

**Comment by mikhaylov-ya** [comment]
Беру

**Comment by fey** [comment]
Супер, спасибо :+1:
